//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComponentTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComponentTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1&quot;,&quot;Brad&quot;,&quot;Wood&quot;,&quot;bwood@chathamfinancial.com&quot;,&quot;Chatham&quot;,&quot;Finance&quot;
        ///&quot;2&quot;,&quot;Jimmy&quot;,&quot;Dean&quot;,&quot;jimmy@dean.com&quot;,&quot;Jimmy Dean Sausages&quot;,&quot;Food Service&quot;
        ///&quot;3&quot;,&quot;Matt&quot;,&quot;Henry&quot;,&quot;matt@logos.org&quot;,&quot;Bible Society&quot;,&quot;Clergy&quot;&quot;4&quot;,&quot;Nuther&quot;,&quot;Dude&quot;,&quot;nuther@dude.com&quot;,&quot;Dudes R Us&quot;,&quot;Ranching&quot;&quot;4&quot;,&quot;Nuther&quot;,&quot;Dude&quot;,&quot;nuther@dude.com&quot;,&quot;Dudes R Us&quot;,&quot;Ranching&quot;
        ///&quot;4&quot;,&quot;Nuther&quot;,&quot;Dude&quot;,&quot;nuther@dude.com&quot;,&quot;Dudes R Us&quot;,&quot;Ranching&quot;
        ///&quot;5&quot;,&quot;John&quot;,&quot;Henry&quot;,&quot;jhenry@us.gov&quot;,&quot;The Patriots&quot;,&quot;Government&quot;
        ///.
        /// </summary>
        internal static string Registrant {
            get {
                return ResourceManager.GetString("Registrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1&quot;,&quot;1&quot;,,&quot;1&quot;
        ///&quot;2&quot;,&quot;4&quot;,,&quot;1&quot;,&quot;3&quot;,&quot;5&quot;
        ///&quot;3&quot;,&quot;5&quot;,,&quot;5&quot;
        ///.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h6 class=&quot;alert alert-secondary&quot;&gt;Available Sessions&lt;/h6&gt;
        ///  &lt;hr&gt;&lt;div class=&quot;container&quot;&gt;&lt;div class=&quot;row font-weight-bold&quot;&gt;&lt;div class=&quot;col&quot;&gt;
        ///        Day
        ///      &lt;/div&gt;
        ///      &lt;div class=&quot;col&quot;&gt;
        ///        Title
        ///      &lt;/div&gt;
        ///      &lt;div class=&quot;col&quot;&gt;
        ///        Description
        ///      &lt;/div&gt;
        ///      &lt;div class=&quot;col col-1&quot;&gt;
        ///        &amp;nbsp;
        ///      &lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;div class=&quot;container&quot;&gt;&lt;div class=&quot;row mt-1&quot;&gt;&lt;div class=&quot;col&quot;&gt;Friday&lt;/div&gt;
        ///        &lt;div class=&quot;col session-title-selectable&quot;&gt;Angular&lt;/div&gt;
        ///        &lt;div class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectSessionsComponentRendered {
            get {
                return ResourceManager.GetString("SelectSessionsComponentRendered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1&quot;,&quot;1&quot;,&quot;Monday Morning&quot;,&quot;Wake up, it&apos;s Monday&quot;
        ///&quot;2&quot;,&quot;2&quot;,&quot;Underwater Basketweaving&quot;,&quot;Classic worthless session&quot;
        ///&quot;3&quot;,&quot;3&quot;,&quot;Clean Coding&quot;,&quot;Code like a boss, yo&quot;
        ///&quot;4&quot;,&quot;4&quot;,&quot;Thursday&apos;s Session&quot;,&quot;This session takes place on thursday&quot;
        ///&quot;5&quot;,&quot;5&quot;,&quot;Angular&quot;,&quot;Learn the art of frustration&quot;
        ///.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
    }
}
